### ISSUE TITLE
add doc info

### ISSUE THREAD

**Issue by danunziata** [danunziata/pps_fede_Ferro_2024#12]
En el readme:

Los pasos para contribuir como colaborador del repo en este proyecto son:

"agregar info del pull reuqest para llegar a develop y luego para llegar a main" 

y podemos ver de agregar un file exclusivo de contributing.md para indicar el flujo para alguien externo que quiera contribuir con el repo.

**Comment by federodriguez16** [comment]
Solved. c2ca159
