### ISSUE TITLE
Diagramas como código

### ISSUE THREAD

**Issue by danunziata** [danunziata/pps_fede_Ferro_2024#23]
Los diagramas realizarlos con herramientas que permiten contruir los diagrmas como codigó, para su correcto versionado y reutilización

## Diagramas como código
- [Plantuml](https://www.plantuml.com/plantuml/uml/SyfFKj2rKt3CoKnELR1Io4ZDoSa70000)
- [Mermaind](https://mermaid.live/edit#pako:eNqdklFrwjAUhf9KiC8K2plkuC4bvswXHxRhY3uwQ1JzO4ttKmmKk9r_vmijc2UM2du5955DPm5uiZeZBMzxhxabFXoZBSovwrp4nT0tJiI3oAOF0qOY1zWa2tC77eZml4CboShOEt7yB8u7KOrmRmdr4C3GmNO9bSzNitPN54NNjmeLOtZuk3vqkYHvkX7fIz55DPXwht52OgfXyLnK0tLYkiO_T6oqUKBkA_Ut02vQxKa2tZrXnSMsIt-4bux4QxZFIbuG1-WawLQB7GyXxPQvYnompj-IaZOY_pOYNonZr8T0kpidid3n9nrD_VhZpUSCpmAOmf1plVe5KO7iFHQqYmnvrbRPowCbFaQQYG6lhEgUiQlwoCprFYXJnndqibnRBXRxsZHCwCgWdn_pqQkyNpme1Cd8vOTqC6Eo8yU)
- [Structurizr](https://structurizr.com/)
- [Diagrams](https://diagrams.mingrammer.com/)
- 
## Referencia
- https://icepanel.medium.com/top-7-diagrams-as-code-tools-for-software-architecture-1a9dd0df1815

## Entrega
- Construir los diagramas del proyecto como código

**Comment by federodriguez16** [comment]
La documentacion se encuentra en metodologia.md
