### ISSUE TITLE
Rootless container

### ISSUE THREAD

**Issue by danunziata** [danunziata/pps_fede_Ferro_2024#34]
# ROOTLESS containers

- [x] Revisar la documentacion para mitigar en nuestro diseño esta vulnerabilidad

## Escalating privileges

Escalating privileges on a target Linux host by using Docker breakout techniques

View link: https://juggernaut-sec.com/docker-breakout-lpe/

## **Rootless containers**

Rootless containers refers to the ability for an unprivileged user to create, run and otherwise manage containers. This term also includes the variety of tooling around containers that can also be run as an unprivileged user.

“Unprivileged user” in this context refers to a user who does not have any administrative rights, and is “not in the good graces of the administrator” (in other words, they do not have the ability to ask for more privileges to be granted to them, or for software packages to be installed).

Pros:
- Can mitigate potential container-breakout vulnerabilities (Not a panacea, of course)
- Friendly to shared machines, especially in HPC environments

Cons:
- Complexity

View link: https://rootlesscontaine.rs/

## Rootless in k3s
View link: https://docs.k3s.io/advanced#running-rootless-servers-experimental

**Comment by federodriguez16** [comment]
Documentacion disponible en 1234018
