### ISSUE TITLE
Service Mesh

### ISSUE THREAD

**Issue by danunziata** [danunziata/pps_fede_Ferro_2024#40]
Obtener performance de PODS y sus CONTENEDORES (aplicaciones), con visulización  de métricas , dentro de un cluster kubernetes utilizando **Servish Mesh**, permitiendo agregar trazabiliad, seguridad y observavilidad de comportamiento al cluster.

Compare servish mesh: 

- https://istio.io/
- https://linkerd.io/
- https://www.consul.io/

## obtener
- github tracing 
- google trends

## documentar conepctos generales 
- [x] service mesh

- [x] Seleccionar 2 service mesh y armar un laboratorio para cada uno, comparar y documentar

## Referencias
- https://overcast.blog/kubernetes-host-networking-configurations-on-the-master-node-4c5fd1995e55
- https://www.youtube.com/watch?v=s3I1kKKfjtQ
- https://www.youtube.com/watch?v=TAlpaC_NSUw
- https://www.youtube.com/watch?v=nawwLTs0KyY

**Comment by federodriguez16** [comment]
Documentado en a9f97bb
