### ISSUE TITLE
Configuracion Mkdocs

### ISSUE THREAD

**Issue by federodriguez16** [danunziata/pps_fede_Ferro_2024#8]
Habria que configurar el repo para que en, la seccion de github pages, poner que se base en la rama gh-pages para que aparezca la pagina en el url. Pero no tengo acceso a la configuracion del repo. Dejo imagen abajo:

![image](https://github.com/danunziata/pps_fede_Ferro_2024/assets/112288610/c2c8b4a6-f78d-46f9-ac28-117cebad2bc9)

**Comment by danunziata** [comment]
solved

se hizo publico el repositorio y se agrego la rama gh-pages en la configuración de pages de github
